language: python
python:
  - "3.6"
script: pytest
notifications:
  email:
    recipients:
      - ogoltsov.i@phystech.edu
    on_success: never # default: change
    on_failure: always # default: always
